# templates/test-job-template.yml
parameters:
  - name: jobName
    type: string
  - name: displayName
    type: string
  - name: testScript
    type: string
  - name: environmentVariables
    type: object
    default: {}

jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.displayName }}
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - task: NodeTool@0
        displayName: "Use Node.js"
        inputs:
          versionSpec: "20.x"

      - task: Npm@1
        displayName: "Install dependencies"
        inputs:
          command: "ci"

      - task: PowerShell@2
        displayName: "Run Tests"
        continueOnError: true
        env:
          CI: "true"
          ${{ insert }}: ${{ parameters.environmentVariables }}
        inputs:
          targetType: "inline"
          script: |
            npx playwright install chromium
            ${{ parameters.testScript }}

      # Archive trace files properly
      - task: ArchiveFiles@2
        displayName: "Archive Trace Files"
        condition: succeededOrFailed()
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)/test-results/**/*.trace"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/traces.zip"
          replaceExistingArchive: true

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "**/results.xml"
          testRunTitle: "${{ parameters.displayName }}"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Test Reports"
        condition: succeededOrFailed()
        inputs:
          PathtoPublish: "$(System.DefaultWorkingDirectory)/playwright-report"
          ArtifactName: "${{ parameters.jobName }}-results"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Traces"
        condition: succeededOrFailed()
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/traces.zip"
          ArtifactName: "${{ parameters.jobName }}-traces"

      # Still publish test-results for videos and screenshots
      - task: PublishBuildArtifacts@1
        displayName: "Publish Test Videos/Screenshots"
        condition: succeededOrFailed()
        inputs:
          PathtoPublish: "$(System.DefaultWorkingDirectory)/test-results"
          ArtifactName: "${{ parameters.jobName }}-test-artifacts"
