trigger:
- none

pool:
  vmImage: windows-latest

jobs:
# -------------------------------
# MDA Tests Job
# -------------------------------
- job: MDA_Tests
  displayName: Run MDA Tests
  steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - task: NodeTool@0
    displayName: 'Use Node.js 18.x'
    inputs:
      versionSpec: '18.x'
      checkLatest: true

  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      command: 'ci'

  - task: PowerShell@2
    displayName: 'Run MDA Tests'
    env:
      APP_URL: '$(MDA_URL)'
      APP_NAME: '$(APP_NAME)'
      O365_USERNAME: '$(O365Username)'
      O365_PASSWORD: '$(O365Password)'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "APP_URL: $env:APP_URL"
        npx playwright install chromium
        npm run test:mda

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/results.xml'

  # - task: mightoria-playwrightForPowerPlatformAdvanced@1
  #   inputs:
  #     testLocation: '$(System.DefaultWorkingDirectory)/tests/mda'
  #     browser: 'chromium'
  #     trace: 'on'
  #     outputLocation: '$(System.DefaultWorkingDirectory)'
  #     appUrl: 'https://futuretrsbuild.crm11.dynamics.com/main.aspx?appid=a38e444a-c33a-ef11-a317-002248c65cbe'
  #     appName: 'TRACS'
  #     o365Username: '$(O365UserName)'
  #     o365Password: '$(O365Password)'
  #     dynamicsUrl: 'https://futuretrsbuild.crm11.dynamics.com/'
  #     clientId: '9e65885f-e920-41b3-a0ef-9a3212cd8ab0'
  #     clientSecret: '$(ClientSecret)'
  #     userRole: 'TRA Case Editor'
  #     team: 'futuretrstest'
  #     businessUnit: 'futuretrstest'

  # - task: ArchiveFiles@2
  #   inputs:
  #     rootFolderOrFile: '$(System.DefaultWorkingDirectory)/playwright-report'
  #     includeRootFolder: true
  #     archiveType: 'zip'
  #     archiveFile: '$(Build.ArtifactStagingDirectory)/test-results/playwright-report.zip'
  #     replaceExistingArchive: true

  # - task: PublishBuildArtifacts@1
  #   inputs:
  #     PathtoPublish: '$(Build.ArtifactStagingDirectory)/test-results'
  #     ArtifactName: 'playwright-report'

  # - task: PublishTestResults@2
  #   inputs:
  #       testResultsFormat: 'JUnit'
  #       testResultsFiles: '**/TEST-*.xml'
  
# -------------------------------
# Portal Tests Job
# -------------------------------
# - job: Portal_Tests
#   displayName: Run Portal Tests
#   steps:
#   - checkout: self
#     persistCredentials: true
#     clean: true

#   - task: mightoria-playwrightForPowerPlatform@1
#     displayName: Portal Tests
#     inputs:
#       testLocation: '$(System.DefaultWorkingDirectory)/tests/portal'
#       browser: 'chromium'
#       trace: 'on'
#       outputLocation: '$(Build.ArtifactStagingDirectory)/tests-portal'
#       appUrl: 'https://future-trs.powerappsportals.com/'
#       appName: 'TRACS'
#       o365Username: '$(O365UserName)'
#       o365Password: '$(O365Password)'

#   - task: ArchiveFiles@2
#     displayName: Archive Portal Tests
#     inputs:
#       rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/tests-portal'
#       includeRootFolder: true
#       archiveType: 'zip'
#       archiveFile: '$(Build.ArtifactStagingDirectory)/archiveFiles/playwright-portal-tests-report.zip'
#       replaceExistingArchive: true

#   - publish: $(Build.ArtifactStagingDirectory)/archiveFiles/
#     artifact: portal-report
#   - task: PublishTestResults@2
#     displayName: Publish Test Results
#     inputs:
#       testResultsFormat: 'JUnit'
#       testResultsFiles: '**/TEST-*.xml'
#       searchFolder: '$(Build.ArtifactStagingDirectory)'
#       mergeTestResults: true
      # failTaskOnFailedTests: true
      # failTaskOnFailureToPublishResults: true
      # failTaskOnMissingResultsFile: true

# -------------------------------
# Public File Tests Job
# -------------------------------
# - job: PublicFile_Tests
#   displayName: Run Public File Tests
#   steps:
#   - checkout: self
#     persistCredentials: true
#     clean: true

#   - task: mightoria-playwrightForPowerPlatform@1
#     displayName: Public File Tests
#     inputs:
#       testLocation: '$(System.DefaultWorkingDirectory)/tests/public-file'
#       browser: 'chromium'
#       trace: 'on'
#       outputLocation: '$(Build.ArtifactStagingDirectory)/tests-public-file'
#       appUrl: 'https://future-trs.powerappsportals.com/'
#       appName: 'TRACS'
#       o365Username: '$(O365UserName)'
#       o365Password: '$(O365Password)'

#   - task: ArchiveFiles@2
#     displayName: Archive Public File Tests
#     inputs:
#       rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/tests-public-file'
#       includeRootFolder: true
#       archiveType: 'zip'
#       archiveFile: '$(Build.ArtifactStagingDirectory)/archiveFiles/playwright-public-file-tests-report.zip'
#       replaceExistingArchive: true

#   - publish: $(Build.ArtifactStagingDirectory)/archiveFiles/
#     artifact: public-file-report

#   - task: PublishTestResults@2
#     displayName: Publish Test Results
#     inputs:
#       testResultsFormat: 'JUnit'
#       testResultsFiles: '**/TEST-*.xml'
#       searchFolder: '$(Build.ArtifactStagingDirectory)'
#       mergeTestResults: true
  #     failTaskOnFailedTests: true
  #     failTaskOnFailureToPublishResults: true
  #     failTaskOnMissingResultsFile: true

