trigger:
- none

pool:
  vmImage: windows-latest

jobs:
# -------------------------------
# MDA Tests Job
# -------------------------------
- job: MDA_Tests
  displayName: Run MDA Tests
  steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - task: mightoria-playwrightForPowerPlatform@1
    displayName: MDA Tests
    inputs:
      testLocation: '$(System.DefaultWorkingDirectory)/tests/mda'
      browser: 'chromium'
      trace: 'on'
      outputLocation: '$(Build.ArtifactStagingDirectory)/tests-mda'
      appUrl: 'https://futuretrsbuild.crm11.dynamics.com/main.aspx?appid=a38e444a-c33a-ef11-a317-002248c65cbe'
      appName: 'TRACS'
      o365Username: '$(O365UserName)'
      o365Password: '$(O365Password)'

  - task: ArchiveFiles@2
    displayName: Archive MDA Tests
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/tests-mda'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/archiveFiles/playwright-mda-tests-report.zip'
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/archiveFiles/
    artifact: mda-report

# -------------------------------
# Portal Tests Job
# -------------------------------
- job: Portal_Tests
  displayName: Run Portal Tests
  steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - task: mightoria-playwrightForPowerPlatform@1
    displayName: Portal Tests
    inputs:
      testLocation: '$(System.DefaultWorkingDirectory)/tests/tests-portal'
      browser: 'chromium'
      trace: 'on'
      outputLocation: '$(Build.ArtifactStagingDirectory)/tests-portal'
      appUrl: 'https://future-trs.powerappsportals.com/'
      appName: 'TRACS'
      o365Username: '$(O365UserName)'
      o365Password: '$(O365Password)'

  - task: ArchiveFiles@2
    displayName: Archive Portal Tests
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/tests-portal'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/archiveFiles/playwright-portal-tests-report.zip'
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/archiveFiles/
    artifact: portal-report

# -------------------------------
# Public File Tests Job
# -------------------------------
- job: PublicFile_Tests
  displayName: Run Public File Tests
  steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - task: mightoria-playwrightForPowerPlatform@1
    displayName: Public File Tests
    inputs:
      testLocation: '$(System.DefaultWorkingDirectory)/tests/public-file'
      browser: 'chromium'
      trace: 'on'
      outputLocation: '$(Build.ArtifactStagingDirectory)/tests-public-file'
      appUrl: 'https://future-trs.powerappsportals.com/'
      appName: 'TRACS'
      o365Username: '$(O365UserName)'
      o365Password: '$(O365Password)'

  - task: ArchiveFiles@2
    displayName: Archive Public File Tests
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/tests-public-file'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/archiveFiles/playwright-public-file-tests-report.zip'
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/archiveFiles/
    artifact: public-file-report

# -------------------------------
# Final Job: Publish Artifacts & Results
# -------------------------------
- job: Publish_Artifacts
  displayName: Publish All Artifacts and Results
  dependsOn:
    - MDA_Tests
    - Portal_Tests
    - PublicFile_Tests
  steps:
  - download: current
    artifact: mda-report

  - download: current
    artifact: portal-report

  - download: current
    artifact: public-file-report

  - task: PublishPipelineArtifact@1
    displayName: Publish Combined Report Artifact
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: playwright-report

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
      searchFolder: '$(Pipeline.Workspace)'
      mergeTestResults: true
      failTaskOnFailedTests: true
      failTaskOnFailureToPublishResults: true
      failTaskOnMissingResultsFile: true
  - task: commitToRepo@2
    displayName: Commit Results to Repo
    inputs:
      commitMsg: '$(Date:yyyyMMdd)$(Rev:.r)'
      branchName: 'results'
