trigger:
  branches:
    include:
      - main
  paths:
    include:
      - tests/*
    exclude:
      - README.md
      - pipelines/*

pool:
  vmImage: windows-latest

jobs:
  - template: templates/playwright-powerplatform-test-job-template.yml
    parameters:
      jobName: 'MDA_Tests'
      displayName: 'Run MDA Tests'
      testLocation: '$(System.DefaultWorkingDirectory)/tests/mda'
      browser: 'chromium'
      trace: 'on'
      outputLocation: '$(Build.ArtifactStagingDirectory)/mda-test-output'
      appUrl: '$(MDA_URL)'
      appName: '$(APP_NAME)'
      o365Username: '$(O365Username)'
      o365Password: '$(O365Password)'