resources:
  pipelines:
  - pipeline: minimal-trigger
    source: minimal-trigger  # Replace with your minimal pipeline name
    trigger:
      branches:
        include:
        - main

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - tests/*
    exclude:
      - README.md
      - pipelines/*

parameters:
  - name: runMDA
    displayName: "Run MDA Tests"
    type: boolean
    default: true

  - name: runPortal
    displayName: "Run Portal Tests"
    type: boolean
    default: true

  - name: runPublicFile
    displayName: "Run Public File Tests"
    type: boolean
    default: true

pool:
  vmImage: windows-latest

jobs:
  # MDA Tests
  - ${{ if eq(parameters.runMDA, true) }}:
      - template: templates/test-job-template.yml
        parameters:
          jobName: "MDA_Tests"
          displayName: "Run MDA Tests"
          testScript: "npm run test:mda"
          environmentVariables:
            MDA_URL: "$(MDA_URL)"
            APP_NAME: "$(APP_NAME)"
            O365_USERNAME: "$(O365Username)"
            O365_PASSWORD: "$(O365Password)"

  # Portal Tests
  - ${{ if eq(parameters.runPortal, true) }}:
      - template: templates/test-job-template.yml
        parameters:
          jobName: "Portal_Tests"
          displayName: "Run Portal Tests"
          testScript: "npm run test:portal"
          environmentVariables:
            PORTAL_URL: "$(PORTAL_URL)"
            O365_USERNAME: "$(O365Username)"
            O365_PASSWORD: "$(O365Password)"

  # Public File Tests
  - ${{ if eq(parameters.runPublicFile, true) }}:
      - template: templates/test-job-template.yml
        parameters:
          jobName: "PublicFile_Tests"
          displayName: "Run Public File Tests"
          testScript: "npm run test:public-file"
          environmentVariables:
            AZURE_APP_URL: "$(AZURE_APP_URL)"
            AZURE_PASSWORD: "$(AZURE_PASSWORD)"
            PORTAL_URL: "$(PORTAL_URL)"
